[build]
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[dev]
    framework = "#custom"
    command = "npm eun dev"
    targetPort = 8080
    port = 5000
    publish = "dist"
    autoLaunch = false 